drop table if exists board CASCADE;
create table board(
    board_id bigint generated by default as identity,
    title varchar(255),
    author varchar(255),
    create_time timestamp,
    contents character(300),
    primary key (board_id)
);

insert into board (title, author, create_time, contents)
values ('진성아 넌 최고야', '윤지원', '2023-04-04', '진성이가 오늘 나와 함께 Spring 공부를 해줬다.')
insert into board (title, author, create_time, contents)
values ('용소희 존멋탱', '윤지콩', '2023-04-04 01:57:00', '오류해결 존멋탱')